findmax:
	javac Node.java Receiver.java Util.java
	java Node findmax

g:
	python g.py

testall:
	javac Node.java Receiver.java Util.java
	java Node testall > waves2.txt
	python p.py

testbits:
	javac Node.java Receiver.java Util.java
	java Node testbits > waves2.txt
	python testbits.py


testeach:
	javac Node.java Receiver.java Util.java
	java Node testeach > waves2.txt
	python testeach.py

findprem:
	javac Node.java Receiver.java Util.java
	java Node findprem
	python prem.py

decode:
	javac Node.java Receiver.java Util.java
	java Node decode > OUTPUT.txt
	python diff.py